### ISSUE TITLE
Get rid of registry.xml

### ISSUE THREAD

**Issue by floooh** [floooh/fips#17]
There should not be a central registry, instead git URLs should be more flexible:

With the short form 'floooh/oryol', fips should assume that the project is on github, otherwise the URL is expected to be a full git URL.

**Comment by floooh** [comment]
Also allow a '#' to define a git branch or tag, e.g.:

```
./fips clone floooh/oryol#fips

./fips clone https://github.com/floooh/oryol.git#fips

./fips clone git@github.com:floooh/oryol.git#fips
```

**Comment by mgerhardy** [comment]
It would be very nice to have an option to download the code from an url - and only have the yml files in some global git repo on a per-lib-basis. That way it would be a lot easier to update versions. See the MXE way to handle this.

You could for example reference an official release by just giving the official download url for e.g. a tar archive and let. If that would be possible, if would be sufficient to provide a yml file with that url, and a CMakeLists.txt to build the extracted source.

All you have to do to update something to a newer version would then be to update the url.

Repository example:
fipsrepo.git
```
  \- zlib
     \- fips.yml (with URL to official download side)
     \- CMakeLists.txt (to build the extracted archive)
  \- simpleai
     \- fips.yml (git repo - but with the ability to override the CMakeLists.txt to use the fips related cmake file)
     \- CMakeLists.fips.txt
```

Libs are now able to provide their own fips support. I don't think this is possible right now if they already use CMake as build system, no?

**Comment by floooh** [comment]
Hmm that's an interesting idea... at least with the libs I have 'fipsified' so far this should be possible. For instance in fips-glfw (https://github.com/floooh/fips-glfw) I'm basically ignoring the glfw CMakeLists.txt files and add my own fips-compatible CMakeLists.txt file in the root directory, and additionally a glfw_config.h file which is normally created by the original glfw cmake files. So it is the original glfw projects in a git submodule, plus a few fips specific files in the project root directory...

The central fips repo would hold those fips-files, plus the information where the original git repo is, and the fips-import process would put the stuff together (not much more complicated then it is now I guess).

At least for simple external which compile to a single library this should be possible.

**Comment by code-disaster** [comment]
Some more ideas to throw in:

- A way to supersede a module for a project, e.g. to allow cloning a dependency of a fips module from a different Git repository. Say I want to compile fips-hello-world, but use a different fips-hello-dep2 repository.
- When there's an option to specify a Git branch/tag, an exact commit hash might be useful too.
- An easier way to reference dependencies on the local file system, with relative paths to the project folder. It works already with file:///... Git repositories, but that's somewhat inconvenient.

**Comment by floooh** [comment]
I think the next step would be a more elaborate way to define an import:

```yaml
imports:
    fips-hello-dep:      # name of the import, will be the directory name
        # free choice of git URL:
        git:     https://github.com/floooh/bla.git
        # branch, tag or revision (SHA-1, depdending on version control system)
        branch/tag/revision:
        # just point to a local path, don't do any remote fetching
        path:
        # optional other ways to fetch remote files
        svn / hg / tar... : 
```

**Comment by floooh** [comment]
I have started to implement this, currently only git: and branch: is implemented (branch: can be a branch or a tag). Directly git-cloning an untagged revision doesn't seem as trivial as 'git clone --branch x', so I didn't implement this yet. The old format still works as expected and gives an 'obsolete' warning.

Example from Oryol's fips.yml:
```yaml
imports:
    gliml:
        git: https://github.com/floooh/gliml.git
    fips-glm:
        git: https://github.com/floooh/fips-glm.git
    fips-unittestpp:
        git: https://github.com/floooh/fips-unittestpp.git
    fips-zlib:
        git: https://github.com/floooh/fips-zlib.git
    fips-glfw:
        git: https://github.com/floooh/fips-glfw.git
    fips-libcurl:
        git: https://github.com/floooh/fips-libcurl.git
```
