### ISSUE TITLE
Ability to filter imports by cmake defines

### ISSUE THREAD

**Issue by floooh** [floooh/fips#69]
There are projects which only need to import external dependencies for their sample executables, but not when importing the project somewhere else. For this, and similar requirements, it should be possible to control the inclusion of an imported project in the fips.yml file:

```yaml
imports:
    git:    https://tralala/blub/blob.git
    if: "NOT FIPS_IMPORT AND FIPS_WINDOWS"
```

The string behind the if: is the expression of a cmake if() statement. If an if: key exists, the import section in the generated .fips-imports.cmake file will be surrounded with an if() (the dependency will always be fetched to the local filesystem, it will only not be integrated into the build project depending on the if expression...
